id: IB14B913B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:41:19+00:00'
last_modified: '2022-06-07T22:06:29.414966+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15366
  title: མདོ་སྔགས་བཀའ་འགྱུར་དཀར་ཆག་དང་བཀའ་འགྱུར་རོ་ཅོག་གི་དཀར་ཆག་བསྟན་པ་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7532':
      image_group_id: I1KG15393
      title: ''
      total_pages: 212
      order: 1
      base_file: 7532.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
